{
 "title": "Smartwatch Heartrate - Dashboard",
 "description": "Dashboard for visualizing productive data streams of kafka cluster \"data_eng_backend\" representing heart rate values of an smartwatch IoT sensor. ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of sensors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(DISTINCT sensor_id) FROM \"topic_upload_data\""
    }
   ]
  },
  {
   "title": "Overall - max. value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MAX(current_value) FROM topic_upload_data"
    }
   ]
  },
  {
   "title": "Overall - min. value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MIN(current_value) FROM topic_upload_data"
    }
   ]
  },
  {
   "title": "Overall - mean value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MEAN(mean_value) FROM topic_upload_data"
    }
   ]
  },
  {
   "title": "Latest sample time",
   "type": "logs",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "SELECT LAST(timestamp) FROM topic_upload_data"
    }
   ]
  },
  {
   "title": "S1 - Heart beat data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "SELECT * FROM \"topic_upload_data\" WHERE sensor_id = 1;"
    }
   ]
  },
  {
   "title": "S2 - Heart beat data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 3 },
   "targets": [
    {
     "query": "SELECT * FROM \"topic_upload_data\" WHERE sensor_id = 2;"
    }
   ]
  },
  {
   "title": "S3 - Heart beat data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 3 },
   "targets": [
    {
     "query": "SELECT * FROM \"topic_upload_data\" WHERE sensor_id = 3;"
    }
   ]
  },
  {
   "title": "S4 - Heart beat data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 3 },
   "targets": [
    {
     "query": "SELECT * FROM \"topic_upload_data\" WHERE sensor_id = 4;"
    }
   ]
  },
  {
   "title": "S5 - Heart beat data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 3 },
   "targets": [
    {
     "query": "SELECT * FROM \"topic_upload_data\" WHERE sensor_id = 5;"
    }
   ]
  },
  {
   "title": "S6 - Heart beat data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "SELECT * FROM \"topic_upload_data\" WHERE sensor_id = 6;"
    }
   ]
  },
  {
   "title": "S7 - Heart beat data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 12 },
   "targets": [
    {
     "query": "SELECT * FROM \"topic_upload_data\" WHERE sensor_id = 7;"
    }
   ]
  },
  {
   "title": "S8 - Heart beat data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 12 },
   "targets": [
    {
     "query": "SELECT * FROM \"topic_upload_data\" WHERE sensor_id = 8;"
    }
   ]
  },
  {
   "title": "S9 - Heart beat data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "SELECT * FROM \"topic_upload_data\" WHERE sensor_id = 9;"
    }
   ]
  },
  {
   "title": "S10 - Heart beat data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 12 },
   "targets": [
    {
     "query": "SELECT * FROM \"topic_upload_data\" WHERE sensor_id = 10;"
    }
   ]
  }
 ]
}